### PR TITLE
Possible fix for #15

### PR DESCRIPTION
**Pull request by leojpod**
Possible fix for #15. 

As I couldn't see what was wrong, I thought to ask elm-json to reinstall the dependencies and see if it would come up with something different. It does seem to restrict a bit the version of `elm/core` which might deal with the dependency issue reported in #15.

### CODE REVIEW

**Comment by CharlonTank** [comment]
I think it doesn't cost anything to deploy this version anyway ;)

**Comment by Lattyware** [comment]
This repo is generated, so I made the change upstream in the generator and main now has this change in.

**Comment by CharlonTank** [comment]
Thank you!

I still get this error, I will try to build it myself and see.

**Comment by Lattyware** [comment]
> Thank you!
> 
> I still get this error, I will try to build it myself and see.

I may have misunderstood, were you getting this error trying to use the package directly from the Elm repo? If so I'll need to publish a new version to fix it, although again I can't reproduce.

Could you give an example of exactly what you were trying to do to get the error? I'll reopen #15

**Comment by leojpod** [comment]
@Lattyware I tried to use your module in an elm-pages project, it "installed" successfully but when compiling it showed the error. 
At first I thought it was `lamdera` shenanigans but I've tried to build the part of the project that uses it with `elm make` and got the same issue.

**Pull request closed without merging**
